import type { Settings, SettingsPatch } from '../types';

export const DEFAULT_SETTINGS: Settings = {
  engine: {
    inactivityThresholdSec: 120,
    awayThresholdSec: 300,
    absenceThresholdSec: 60,
    offScreenPolicy: 'neutral',
    productiveThreshold: 0.6,
    neutralThreshold: 0.35,
    neutralContribution: 0.5,
    weights: { relevance: 0.3, input: 0.2, document: 0.25, camera: 0.15, context: 0.1 },
  },
  analysisIntervalSec: 5,
  monitoring: {
    webcam: false,
    screenAnalysis: true,
    activeWindow: true,
    inputActivity: true,
    documents: true,
  },
  apps: {
    productiveApps: [
      'winword',
      'code',
      'cursor',
      'devenv',
      'idea64',
      'pycharm64',
      'webstorm64',
      'rstudio',
      'matlab',
      'notepad',
      'notepad++',
      'sublime_text',
      'obsidian',
      'onenote',
      'excel',
      'powerpnt',
      'acrobat',
      'acrord32',
      'sumatrapdf',
      'zotero',
      'windowsterminal',
      'powershell',
      'cmd',
      'texstudio',
      'anki',
    ],
    distractingApps: ['steam', 'epicgameslauncher', 'discord', 'whatsapp', 'telegram', 'netflix', 'battle.net'],
    excludedApps: ['focusproof', 'electron', 'explorer', 'lockapp', 'searchhost', 'shellexperiencehost'],
    productiveKeywords: [
      'stack overflow',
      'scholar',
      'wikipedia',
      'arxiv',
      'jstor',
      'moodle',
      'canvas',
      'blackboard',
      'documentation',
      'docs',
      'mdn',
      'github',
      'overleaf',
      'khan academy',
      'coursera',
      'pubmed',
    ],
    distractingKeywords: [
      'youtube',
      'netflix',
      'reddit',
      'twitter',
      ' / x',
      'instagram',
      'tiktok',
      'facebook',
      'twitch',
      'prime video',
      'disney+',
      '9gag',
    ],
  },
  privacy: { storeWindowTitles: true },
  camera: { samplesPerSecond: 2, lookAwayAngleDeg: 25, zones: [] },
  overlay: {
    enabled: true,
    corner: 'top-right',
    displayId: null,
    size: 'small',
    details: { label: false, focusScore: false, alt: false, camera: false },
  },
};

/** Deep-merges a validated patch into settings; arrays are replaced, not concatenated. */
export function mergeSettings(base: Settings, patch: SettingsPatch): Settings {
  return {
    engine: {
      ...base.engine,
      ...patch.engine,
      weights: { ...base.engine.weights, ...patch.engine?.weights },
    },
    analysisIntervalSec: patch.analysisIntervalSec ?? base.analysisIntervalSec,
    monitoring: { ...base.monitoring, ...patch.monitoring },
    apps: { ...base.apps, ...patch.apps },
    privacy: { ...base.privacy, ...patch.privacy },
    camera: { ...base.camera, ...patch.camera },
    overlay: {
      ...base.overlay,
      ...patch.overlay,
      details: { ...base.overlay.details, ...patch.overlay?.details },
    },
  };
}
